
DELETE FROM NSPUBMART.CMSC_INVST_CNT_HLD_MKT_VAL
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO NSPUBMART.CMSC_INVST_CNT_HLD_MKT_VAL
SELECT 
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,T1.CLSF_2 AS TZZFL
,T1.TZZSL AS TZZSL
,T1.TZZSL/T2.TZZZS AS TZZSLZB
FROM
(
	SELECT b.CLSF_2
	,COUNT(DISTINCT a.OAP_ACCT_NBR) AS TZZSL
	FROM (
		SELECT	oap_acct_nbr
		FROM	NSOVIEW.CSDC_INTG_UAP_SEC_ACCT	---统一账户平台证券账户表
		WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM NSPVIEW.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
		  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM NSPVIEW.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
		  AND	SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
		  AND	SEC_ACCT_STS  NOT IN ('03','04')
		GROUP BY 1
		) a
	LEFT JOIN	
		(
			SELECT	oap_acct_nbr	--一码通账户号码
					,clsf_1		--一级分类
					,clsf_2		--二级分类
					,sec_acct_sort
			FROM	NSPVIEW.ACT_STK_INVST_CLSF_HIS	---股票投资者分类表
			WHERE	s_date <= (
					SELECT MAX(CALENDAR_DATE) 
					FROM NSPVIEW.PTY_TRAD_CLND
					WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND IF_TRADDAY = 1
				)
			AND	e_date >  (
					SELECT MAX(CALENDAR_DATE) 
					FROM NSPVIEW.PTY_TRAD_CLND
					WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND IF_TRADDAY = 1
				)
			 AND clsf_1 =’1000’
			GROUP BY 1,2,3,4
		) b 
	ON a.oap_acct_nbr = b.oap_acct_nbr
	GROUP BY 1
) T1,
(
	SELECT COUNT(DISTINCT a.OAP_ACCT_NBR) AS TZZZS
	FROM (
		SELECT	oap_acct_nbr
		FROM	NSOVIEW.CSDC_INTG_UAP_SEC_ACCT	---统一账户平台证券账户表
		WHERE	s_date <= (
			SELECT MAX(CALENDAR_DATE) 
			FROM NSPVIEW.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
		  AND	e_date >  (
			SELECT MAX(CALENDAR_DATE) 
			FROM NSPVIEW.PTY_TRAD_CLND
			WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
			AND IF_TRADDAY = 1
		)
		  AND	SEC_ACCT_SORT IN ('11','12','14','15','21','22','24')
		  AND	SEC_ACCT_STS  NOT IN ('03','04')
		GROUP BY 1
		) a
	LEFT JOIN	
		(
			SELECT	oap_acct_nbr	--一码通账户号码
					,clsf_1		--一级分类
					,clsf_2		--二级分类
					,sec_acct_sort
			FROM	NSPVIEW.ACT_STK_INVST_CLSF_HIS	---股票投资者分类表
			WHERE	s_date <= (
					SELECT MAX(CALENDAR_DATE) 
					FROM NSPVIEW.PTY_TRAD_CLND
					WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND IF_TRADDAY = 1
				)
			AND	e_date >  (
					SELECT MAX(CALENDAR_DATE) 
					FROM NSPVIEW.PTY_TRAD_CLND
					WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
					AND IF_TRADDAY = 1
				)
			 AND clsf_1 =’1000’
			GROUP BY 1,2,3,4
		) b 
	ON a.oap_acct_nbr = b.oap_acct_nbr
) T2
WHERE T1.CLSF_2 IS NOT NULL
AND T2.TZZZS IS NOT NULL
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT


