
DELETE FROM NSPUBMART.CMSC_FUTRS_INVST_CNT_EQT
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO NSPUBMART.CMSC_FUTRS_INVST_CNT_EQT
SELECT 
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,T1.FUTRS_INVST_SORT AS TZZFL
,T1.QHTZZSL AS QHTZZSL
,T1.QHTZZSL/T2.QHTZZZS AS QHTZZSLZB
FROM
(
	SELECT 
	FUTRS_INVST_SORT
	,IDX_VAL AS QHTZZSL
	FROM nspubview.KPI_FINVST_UOPACCT_CDE_VOL_IDX
	WHERE STAT_DATE = (
				SELECT MAX(CALENDAR_DATE) 
				FROM NSPVIEW.PTY_TRAD_CLND
				WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
				AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
				AND IF_TRADDAY = 1
			)
	AND IDX_CDE = 'FS001'
	AND FREQ = 'D'
	AND VART_ONE_CLSF = '-1'
	AND EXCH_NBR = '-1'
	AND FUTRS_INVST_SORT <> '-1'
) T1,
(
	SELECT 
	SUM(IDX_VAL) AS QHTZZZS
	FROM nspubview.KPI_FINVST_UOPACCT_CDE_VOL_IDX
	WHERE STAT_DATE = (
				SELECT MAX(CALENDAR_DATE) 
				FROM NSPVIEW.PTY_TRAD_CLND
				WHERE EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
				AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1))
				AND IF_TRADDAY = 1
			)
	AND IDX_CDE = 'FS001'
	AND FREQ = 'D'
	AND VART_ONE_CLSF = '-1'
	AND EXCH_NBR = '-1'
	AND FUTRS_INVST_SORT <> '-1'
) T2
WHERE T1.FUTRS_INVST_SORT IS NOT NULL
AND T2.QHTZZZS IS NOT NULL
;


.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT



