
DELETE FROM ${NSPUBMART}.CMSC_TOT_INVST_CNT
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSPUBMART}.CMSC_TOT_INVST_CNT
SELECT
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,IDX_VAL
FROM ${NSPUBVIEW}.KPI_OAP_ACCT_VOL
WHERE STAT_DATE = (
	SELECT MAX(CALENDAR_DATE) 
	FROM ${NSPVIEW}.PTY_TRAD_CLND
	WHERE CALENDAR_DATE <= ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1)
	AND DAY_OF_MONTH = 1
)
AND ACCT_TYPE = '-1'
AND STK_INVST_SORT = '-1'
AND INVST_OPN_ACCT_PPDM = '-1'
AND IDX_CDE = 'SK018'
AND FREQ = 'M';

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT
