
DELETE FROM NSPUBMART.CMSC_LIST_COMP_DVD_AMT
WHERE TJRQ = SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6)
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO NSPUBMART.CMSC_LIST_COMP_DVD_AMT
SELECT
SUBSTR(CAST(CAST(ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1) AS DATE FORMAT 'YYYYMMDD') AS CHAR(8)),1,6) AS TJRQ
,SUM(CASH_DVD_AMT_BEF_TAX) --现金分红金额（税前）
FROM NSPUBVIEW.MID_STK_DVD
WHERE EXR_EXD_D BETWEEN 
(
	SELECT MAX(CALENDAR_DATE) 
	FROM NSPVIEW.PTY_TRAD_CLND
	WHERE CALENDAR_DATE <= ADD_MONTHS(CAST('${TXDATE}' AS DATE FORMAT 'YYYYMMDD'),-1)
	AND DAY_OF_MONTH = 1
) AND 
(
	SELECT MAX(CALENDAR_DATE)
	FROM NSPVIEW.PTY_TRAD_CLND
	WHERE CALENDAR_DATE < '${TXDATE}'
	AND EOM_SIGN = 1
);

.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT
