CREATE MULTISET TABLE nsPUBMart.CMSC_LIST_COMP_DVD_AMT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	SSGSFHJE TITLE '上市公司分红金额' NOT NULL DECIMAL(24,2)
)
PRIMARY INDEX(TJRQ) ; 
 
 COMMENT ON  nsPUBMart.CMSC_LIST_COMP_DVD_AMT is 'CMSC_J0001_上市公司分红金额';

CREATE MULTISET TABLE nsPUBMart.CMSC_TOT_INVST_CNT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZZRS TITLE '投资者总人数' NOT NULL DECIMAL(24,0)
)
PRIMARY INDEX(TJRQ) ; 
 
 COMMENT ON  nsPUBMart.CMSC_TOT_INVST_CNT is 'CMSC_J0002_投资者数';

CREATE MULTISET TABLE nsPUBMart.CMSC_OPEN_INVST_CNT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	PD TITLE '频度' NOT NULL CHAR(1) CASESPECIFIC,
	ZZRKHS TITLE '自然人开户数' NOT NULL DECIMAL(24,0),
	JGKHS TITLE '机构开户数' NOT NULL DECIMAL(24,0)
)
PRIMARY INDEX(TJRQ,PD) ; 
 
 COMMENT ON  nsPUBMart.CMSC_OPEN_INVST_CNT is 'CMSC_J0003_开户数';

CREATE MULTISET TABLE nsPUBMart.CMSC_INVST_CNT_EDCT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZFL TITLE '投资者分类' NOT NULL CHAR(4) CASESPECIFIC,
	TZZSL TITLE '投资者数量' NOT NULL DECIMAL(24,0),
	TZZSLZB TITLE '投资者数量占比' NOT NULL DECIMAL(5,4)
)
PRIMARY INDEX(TJRQ,TZZFL) ; 
 
 COMMENT ON  nsPUBMart.CMSC_INVST_CNT_EDCT is 'CMSC_J0004_投资者数_按学历分类';

CREATE MULTISET TABLE nsPUBMart.CMSC_INVST_CNT_AGE (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZFL TITLE '投资者分类' NOT NULL CHAR(3) CASESPECIFIC,
	TZZSL TITLE '投资者数量' NOT NULL DECIMAL(24,0),
	TZZSLZB TITLE '投资者数量占比' NOT NULL DECIMAL(5,4)
)
PRIMARY INDEX(TJRQ,TZZFL) ; 
 
 COMMENT ON  nsPUBMart.CMSC_INVST_CNT_AGE is 'CMSC_J0005_投资者数_按年龄分类';

CREATE MULTISET TABLE nsPUBMart.CMSC_INVST_CNT_HLD_MKT_VAL (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZFL TITLE '投资者分类' NOT NULL CHAR(4) CASESPECIFIC,
	TZZSL TITLE '投资者数量' NOT NULL DECIMAL(24,0),
	TZZSLZB TITLE '投资者数量占比' NOT NULL DECIMAL(5,4)
)
PRIMARY INDEX(TJRQ,TZZFL) ; 
 
 COMMENT ON  nsPUBMart.CMSC_INVST_CNT_HLD_MKT_VAL is 'CMSC_J0006_投资者数_按持股市值分类';

CREATE MULTISET TABLE nsPUBMart.CMSC_FUTRS_INVST_CNT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	QHTZZS TITLE '期货投资者数' NOT NULL DECIMAL(24,0)
)
PRIMARY INDEX(TJRQ) ; 
 
 COMMENT ON  nsPUBMart.CMSC_FUTRS_INVST_CNT is 'CMSC_J0007_期货投资者数';

CREATE MULTISET TABLE nsPUBMart.CMSC_FUTRS_INVST_CNT_EQT (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZFL TITLE '投资者分类' NOT NULL CHAR(4) CASESPECIFIC,
	QHTZZSL TITLE '期货投资者数量' NOT NULL DECIMAL(24,0),
	QHTZZSLZB TITLE '期货投资者数量占比' NOT NULL DECIMAL(5,4)
)
PRIMARY INDEX(TJRQ,TZZFL) ; 
 
 COMMENT ON  nsPUBMart.CMSC_FUTRS_INVST_CNT_EQT is 'CMSC_J0008_期货投资者数_按权益分布分类';

CREATE MULTISET TABLE nsPUBMart.CMSC_FUTRS_INVST_CNT_HLD_MKT_VAL (
	TJRQ TITLE '统计日期' NOT NULL CHAR(6) CASESPECIFIC,
	TZZFL TITLE '投资者分类' NOT NULL CHAR(4) CASESPECIFIC,
	CJSL TITLE '成交数量' NOT NULL DECIMAL(24,0),
	CJSLZB TITLE '成交数量占比' NOT NULL DECIMAL(5,4)
)
PRIMARY INDEX(TJRQ,TZZFL) ; 
 
 COMMENT ON  nsPUBMart.CMSC_FUTRS_INVST_CNT_HLD_MKT_VAL is 'CMSC_J0009_投资者交易量_按持股市值分类';


